name: Deploy Cloudflare Worker
on:
  - repository_dispatch
workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@latest
    - name: Build with Node 14.x
    - uses: actions/setup-node@latest
      with:
        node-version: 14
    - run: yarn install
    - run: yarn build
    - name: Publish with Wrangler
      uses: cloudflare/wrangler-action@latest
      with:
        apiToken: ${{ secrets.CF_API_TOKEN }}
      env:
        CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        IS_WORKER: true
